### PR TITLE
Added sorting and saving of some settings in conversations

### PR DESCRIPTION
**Pull request by ttempaa**

### CODE REVIEW

**Comment by Mylinde** [comment]
Sounds great. What also would be great, storing the used provider and model in the conversation string and setting them automatically when going further the conversation at a later time.

**Comment by ttempaa** [comment]
Hmm, that should work.

**Comment by Mylinde** [comment]
Can you add the possibility to toggle the sorting of the conversations true=time/false=alphabetical? Would suggest that it should be simultaneous the existing implement of toggling.

**Comment by Mylinde** [comment]
Saving and setting back the provider and model works like a charme. Thank you very much this is a realy great enhancement.

**Comment by Mylinde** [comment]
button added in my fork.

**Pull request merged**
