### PR TITLE
UI update, added image generator toggle and file upload input

### PR DESCRIPTION
**Pull request by Mylinde**
added toggle for image generator to sidebar and input fields for upload pictures and files to text input area

### CODE REVIEW

**Comment by Mylinde** [comment]
To get this features working as expected we need to merge some code from g4f.

**Comment by VadimBoev** [comment]
Which ones exactly?

**Comment by Mylinde** [comment]
Not sure, wich files exactly affected. Best way would be to take a look in the commits of g4f. So far it looks like it would be chat.json on client side, on server side backend.py,  website.py.

**Comment by VadimBoev** [comment]
Okay, I'll deal with this issue later. Thank you for your contributions to the development of this repository!

**Comment by Mylinde** [comment]
The necessary code for image generating is this commit, but I haven't looked in detail. Looks like we just need to edit backend.py and chat.js. https://github.com/xtekky/gpt4free/pull/1426
For file upload i haven't looked around.

**Comment by Mylinde** [comment]
Closing the pull request because made some additional changes.

**Pull request closed without merging**
